### ISSUE TITLE
Koukyuu_no_Karasu: font package in cooperative version

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#80] opened 2024-02-15 12:53 UTC
I noticed that the BDRip of _Koukyuu no Karasu_ that VCB-Studio collaborated with you on is about to be released. The font package they provide includes 12 fonts, but both the README.md and ListAssFonts state that only 11 fonts are needed.

It looks like this was a mistake. Could you please convey this to them?

**Comment by MIRIMIRIM** [comment] 2024-02-16 00:43
This is an error caused by a bug in [FontLoaderSub](https://github.com/yzwduck/FontLoaderSub). Such relatively minor mistakes may not be fixed in this release and might be worked around in future workflow to avoid this bug.

**Closed by MIRIMIRIM** 2024-02-16 00:43 UTC

**Comment by 3gf8jv4dv** [comment] 2025-02-21 03:59
@MIRIMIRIM view on github
